 cd /data/christian/hdall/results/

 cat 2013-05-29-roi-remap/music/rel/gene_covgs/1021247_rel.covg | perl /mnt/projects/hdall/scripts/remap.pl > current/music/rel/gene_covgs/1021247_rel.covg &
 cat 2013-05-29-roi-remap/music/rel/gene_covgs/314_rel.covg | perl /mnt/projects/hdall/scripts/remap.pl > current/music/rel/gene_covgs/314_rel.covg &
 cat 2013-05-29-roi-remap/music/rel/gene_covgs/399_rel.covg | perl /mnt/projects/hdall/scripts/remap.pl > current/music/rel/gene_covgs/399_rel.covg &
 cat 2013-05-29-roi-remap/music/rel/gene_covgs/430_rel.covg | perl /mnt/projects/hdall/scripts/remap.pl > current/music/rel/gene_covgs/430_rel.covg &
 cat 2013-05-29-roi-remap/music/rel/gene_covgs/446_rel.covg | perl /mnt/projects/hdall/scripts/remap.pl > current/music/rel/gene_covgs/446_rel.covg &
 cat 2013-05-29-roi-remap/music/rel/gene_covgs/460_rel.covg | perl /mnt/projects/hdall/scripts/remap.pl > current/music/rel/gene_covgs/460_rel.covg &
 cat 2013-05-29-roi-remap/music/rel/gene_covgs/545_rel.covg | perl /mnt/projects/hdall/scripts/remap.pl > current/music/rel/gene_covgs/545_rel.covg &
 cat 2013-05-29-roi-remap/music/rel/gene_covgs/592_rel.covg | perl /mnt/projects/hdall/scripts/remap.pl > current/music/rel/gene_covgs/592_rel.covg &
 cat 2013-05-29-roi-remap/music/rel/gene_covgs/715_rel.covg | perl /mnt/projects/hdall/scripts/remap.pl > current/music/rel/gene_covgs/715_rel.covg &
 cat 2013-05-29-roi-remap/music/rel/gene_covgs/786_rel.covg | perl /mnt/projects/hdall/scripts/remap.pl > current/music/rel/gene_covgs/786_rel.covg &
 cat 2013-05-29-roi-remap/music/rel/gene_covgs/792_rel.covg | perl /mnt/projects/hdall/scripts/remap.pl > current/music/rel/gene_covgs/792_rel.covg &
 cat 2013-05-29-roi-remap/music/rel/gene_covgs/818_rel.covg | perl /mnt/projects/hdall/scripts/remap.pl > current/music/rel/gene_covgs/818_rel.covg &
 cat 2013-05-29-roi-remap/music/rel/gene_covgs/842_rel.covg | perl /mnt/projects/hdall/scripts/remap.pl > current/music/rel/gene_covgs/842_rel.covg &
 cat 2013-05-29-roi-remap/music/rel/gene_covgs/A_rel.covg | perl /mnt/projects/hdall/scripts/remap.pl > current/music/rel/gene_covgs/A_rel.covg &
 cat 2013-05-29-roi-remap/music/rel/gene_covgs/B_rel.covg | perl /mnt/projects/hdall/scripts/remap.pl > current/music/rel/gene_covgs/B_rel.covg &
 cat 2013-05-29-roi-remap/music/rel/gene_covgs/C_rel.covg | perl /mnt/projects/hdall/scripts/remap.pl > current/music/rel/gene_covgs/C_rel.covg &
 cat 2013-05-29-roi-remap/music/rel/gene_covgs/D_rel.covg | perl /mnt/projects/hdall/scripts/remap.pl > current/music/rel/gene_covgs/D_rel.covg &
 cat 2013-05-29-roi-remap/music/rel/gene_covgs/E_rel.covg | perl /mnt/projects/hdall/scripts/remap.pl > current/music/rel/gene_covgs/E_rel.covg &
 cat 2013-05-29-roi-remap/music/rel/gene_covgs/X_rel.covg | perl /mnt/projects/hdall/scripts/remap.pl > current/music/rel/gene_covgs/X_rel.covg &
 cat 2013-05-29-roi-remap/music/rel/gene_covgs/Y_rel.covg | perl /mnt/projects/hdall/scripts/remap.pl > current/music/rel/gene_covgs/Y_rel.covg &
 cat 2013-05-29-roi-remap/music/rel/gene_mrs | perl /mnt/projects/hdall/scripts/remap.pl > current/music/rel/gene_mrs &
 cat 2013-05-29-roi-remap/music/rel/roi_covgs/1021247_rel.covg | perl /mnt/projects/hdall/scripts/remap.pl > current/music/rel/roi_covgs/1021247_rel.covg &
 cat 2013-05-29-roi-remap/music/rel/roi_covgs/314_rel.covg | perl /mnt/projects/hdall/scripts/remap.pl > current/music/rel/roi_covgs/314_rel.covg &
 cat 2013-05-29-roi-remap/music/rel/roi_covgs/399_rel.covg | perl /mnt/projects/hdall/scripts/remap.pl > current/music/rel/roi_covgs/399_rel.covg &
 cat 2013-05-29-roi-remap/music/rel/roi_covgs/430_rel.covg | perl /mnt/projects/hdall/scripts/remap.pl > current/music/rel/roi_covgs/430_rel.covg &
 cat 2013-05-29-roi-remap/music/rel/roi_covgs/446_rel.covg | perl /mnt/projects/hdall/scripts/remap.pl > current/music/rel/roi_covgs/446_rel.covg &
 cat 2013-05-29-roi-remap/music/rel/roi_covgs/460_rel.covg | perl /mnt/projects/hdall/scripts/remap.pl > current/music/rel/roi_covgs/460_rel.covg &
 cat 2013-05-29-roi-remap/music/rel/roi_covgs/545_rel.covg | perl /mnt/projects/hdall/scripts/remap.pl > current/music/rel/roi_covgs/545_rel.covg &
 cat 2013-05-29-roi-remap/music/rel/roi_covgs/592_rel.covg | perl /mnt/projects/hdall/scripts/remap.pl > current/music/rel/roi_covgs/592_rel.covg &
 cat 2013-05-29-roi-remap/music/rel/roi_covgs/715_rel.covg | perl /mnt/projects/hdall/scripts/remap.pl > current/music/rel/roi_covgs/715_rel.covg &
 cat 2013-05-29-roi-remap/music/rel/roi_covgs/786_rel.covg | perl /mnt/projects/hdall/scripts/remap.pl > current/music/rel/roi_covgs/786_rel.covg &
 cat 2013-05-29-roi-remap/music/rel/roi_covgs/792_rel.covg | perl /mnt/projects/hdall/scripts/remap.pl > current/music/rel/roi_covgs/792_rel.covg &
 cat 2013-05-29-roi-remap/music/rel/roi_covgs/818_rel.covg | perl /mnt/projects/hdall/scripts/remap.pl > current/music/rel/roi_covgs/818_rel.covg &
 cat 2013-05-29-roi-remap/music/rel/roi_covgs/842_rel.covg | perl /mnt/projects/hdall/scripts/remap.pl > current/music/rel/roi_covgs/842_rel.covg &
 cat 2013-05-29-roi-remap/music/rel/roi_covgs/A_rel.covg | perl /mnt/projects/hdall/scripts/remap.pl > current/music/rel/roi_covgs/A_rel.covg &
 cat 2013-05-29-roi-remap/music/rel/roi_covgs/B_rel.covg | perl /mnt/projects/hdall/scripts/remap.pl > current/music/rel/roi_covgs/B_rel.covg &
 cat 2013-05-29-roi-remap/music/rel/roi_covgs/C_rel.covg | perl /mnt/projects/hdall/scripts/remap.pl > current/music/rel/roi_covgs/C_rel.covg &
 cat 2013-05-29-roi-remap/music/rel/roi_covgs/D_rel.covg | perl /mnt/projects/hdall/scripts/remap.pl > current/music/rel/roi_covgs/D_rel.covg &
 cat 2013-05-29-roi-remap/music/rel/roi_covgs/E_rel.covg | perl /mnt/projects/hdall/scripts/remap.pl > current/music/rel/roi_covgs/E_rel.covg &
 cat 2013-05-29-roi-remap/music/rel/roi_covgs/X_rel.covg | perl /mnt/projects/hdall/scripts/remap.pl > current/music/rel/roi_covgs/X_rel.covg &
 cat 2013-05-29-roi-remap/music/rel/roi_covgs/Y_rel.covg | perl /mnt/projects/hdall/scripts/remap.pl > current/music/rel/roi_covgs/Y_rel.covg &
  
 exit
 
 cat 2013-05-29-roi-remap/music/dia/gene_covgs/1021247_dia.covg | perl /mnt/projects/hdall/scripts/remap.pl > current/music/dia/gene_covgs/1021247_dia.covg &
 cat 2013-05-29-roi-remap/music/dia/gene_covgs/314_dia.covg | perl /mnt/projects/hdall/scripts/remap.pl > current/music/dia/gene_covgs/314_dia.covg &
 cat 2013-05-29-roi-remap/music/dia/gene_covgs/399_dia.covg | perl /mnt/projects/hdall/scripts/remap.pl > current/music/dia/gene_covgs/399_dia.covg &
 cat 2013-05-29-roi-remap/music/dia/gene_covgs/430_dia.covg | perl /mnt/projects/hdall/scripts/remap.pl > current/music/dia/gene_covgs/430_dia.covg &
 cat 2013-05-29-roi-remap/music/dia/gene_covgs/446_dia.covg | perl /mnt/projects/hdall/scripts/remap.pl > current/music/dia/gene_covgs/446_dia.covg &
 cat 2013-05-29-roi-remap/music/dia/gene_covgs/460_dia.covg | perl /mnt/projects/hdall/scripts/remap.pl > current/music/dia/gene_covgs/460_dia.covg &
 cat 2013-05-29-roi-remap/music/dia/gene_covgs/545_dia.covg | perl /mnt/projects/hdall/scripts/remap.pl > current/music/dia/gene_covgs/545_dia.covg &
 cat 2013-05-29-roi-remap/music/dia/gene_covgs/592_dia.covg | perl /mnt/projects/hdall/scripts/remap.pl > current/music/dia/gene_covgs/592_dia.covg &
 cat 2013-05-29-roi-remap/music/dia/gene_covgs/715_dia.covg | perl /mnt/projects/hdall/scripts/remap.pl > current/music/dia/gene_covgs/715_dia.covg &
 cat 2013-05-29-roi-remap/music/dia/gene_covgs/786_dia.covg | perl /mnt/projects/hdall/scripts/remap.pl > current/music/dia/gene_covgs/786_dia.covg &
 cat 2013-05-29-roi-remap/music/dia/gene_covgs/792_dia.covg | perl /mnt/projects/hdall/scripts/remap.pl > current/music/dia/gene_covgs/792_dia.covg &
 cat 2013-05-29-roi-remap/music/dia/gene_covgs/818_dia.covg | perl /mnt/projects/hdall/scripts/remap.pl > current/music/dia/gene_covgs/818_dia.covg &
 cat 2013-05-29-roi-remap/music/dia/gene_covgs/842_dia.covg | perl /mnt/projects/hdall/scripts/remap.pl > current/music/dia/gene_covgs/842_dia.covg &
 cat 2013-05-29-roi-remap/music/dia/gene_covgs/A_dia.covg | perl /mnt/projects/hdall/scripts/remap.pl > current/music/dia/gene_covgs/A_dia.covg &
 cat 2013-05-29-roi-remap/music/dia/gene_covgs/B_dia.covg | perl /mnt/projects/hdall/scripts/remap.pl > current/music/dia/gene_covgs/B_dia.covg &
 cat 2013-05-29-roi-remap/music/dia/gene_covgs/C_dia.covg | perl /mnt/projects/hdall/scripts/remap.pl > current/music/dia/gene_covgs/C_dia.covg &
 cat 2013-05-29-roi-remap/music/dia/gene_covgs/D_dia.covg | perl /mnt/projects/hdall/scripts/remap.pl > current/music/dia/gene_covgs/D_dia.covg &
 cat 2013-05-29-roi-remap/music/dia/gene_covgs/E_dia.covg | perl /mnt/projects/hdall/scripts/remap.pl > current/music/dia/gene_covgs/E_dia.covg &
 cat 2013-05-29-roi-remap/music/dia/gene_covgs/X_dia.covg | perl /mnt/projects/hdall/scripts/remap.pl > current/music/dia/gene_covgs/X_dia.covg &
 cat 2013-05-29-roi-remap/music/dia/gene_covgs/Y_dia.covg | perl /mnt/projects/hdall/scripts/remap.pl > current/music/dia/gene_covgs/Y_dia.covg &
 cat 2013-05-29-roi-remap/music/dia/gene_mrs | perl /mnt/projects/hdall/scripts/remap.pl > current/music/dia/gene_mrs &
 cat 2013-05-29-roi-remap/music/dia/roi_covgs/1021247_dia.covg | perl /mnt/projects/hdall/scripts/remap.pl > current/music/dia/roi_covgs/1021247_dia.covg &
 cat 2013-05-29-roi-remap/music/dia/roi_covgs/314_dia.covg | perl /mnt/projects/hdall/scripts/remap.pl > current/music/dia/roi_covgs/314_dia.covg &
 cat 2013-05-29-roi-remap/music/dia/roi_covgs/399_dia.covg | perl /mnt/projects/hdall/scripts/remap.pl > current/music/dia/roi_covgs/399_dia.covg &
 cat 2013-05-29-roi-remap/music/dia/roi_covgs/430_dia.covg | perl /mnt/projects/hdall/scripts/remap.pl > current/music/dia/roi_covgs/430_dia.covg &
 cat 2013-05-29-roi-remap/music/dia/roi_covgs/446_dia.covg | perl /mnt/projects/hdall/scripts/remap.pl > current/music/dia/roi_covgs/446_dia.covg &
 cat 2013-05-29-roi-remap/music/dia/roi_covgs/460_dia.covg | perl /mnt/projects/hdall/scripts/remap.pl > current/music/dia/roi_covgs/460_dia.covg &
 cat 2013-05-29-roi-remap/music/dia/roi_covgs/545_dia.covg | perl /mnt/projects/hdall/scripts/remap.pl > current/music/dia/roi_covgs/545_dia.covg &
 cat 2013-05-29-roi-remap/music/dia/roi_covgs/592_dia.covg | perl /mnt/projects/hdall/scripts/remap.pl > current/music/dia/roi_covgs/592_dia.covg &
 cat 2013-05-29-roi-remap/music/dia/roi_covgs/715_dia.covg | perl /mnt/projects/hdall/scripts/remap.pl > current/music/dia/roi_covgs/715_dia.covg &
 cat 2013-05-29-roi-remap/music/dia/roi_covgs/786_dia.covg | perl /mnt/projects/hdall/scripts/remap.pl > current/music/dia/roi_covgs/786_dia.covg &
 cat 2013-05-29-roi-remap/music/dia/roi_covgs/792_dia.covg | perl /mnt/projects/hdall/scripts/remap.pl > current/music/dia/roi_covgs/792_dia.covg &
 cat 2013-05-29-roi-remap/music/dia/roi_covgs/818_dia.covg | perl /mnt/projects/hdall/scripts/remap.pl > current/music/dia/roi_covgs/818_dia.covg &
 cat 2013-05-29-roi-remap/music/dia/roi_covgs/842_dia.covg | perl /mnt/projects/hdall/scripts/remap.pl > current/music/dia/roi_covgs/842_dia.covg &
 cat 2013-05-29-roi-remap/music/dia/roi_covgs/A_dia.covg | perl /mnt/projects/hdall/scripts/remap.pl > current/music/dia/roi_covgs/A_dia.covg &
 cat 2013-05-29-roi-remap/music/dia/roi_covgs/B_dia.covg | perl /mnt/projects/hdall/scripts/remap.pl > current/music/dia/roi_covgs/B_dia.covg &
 cat 2013-05-29-roi-remap/music/dia/roi_covgs/C_dia.covg | perl /mnt/projects/hdall/scripts/remap.pl > current/music/dia/roi_covgs/C_dia.covg &
 cat 2013-05-29-roi-remap/music/dia/roi_covgs/D_dia.covg | perl /mnt/projects/hdall/scripts/remap.pl > current/music/dia/roi_covgs/D_dia.covg &
 cat 2013-05-29-roi-remap/music/dia/roi_covgs/E_dia.covg | perl /mnt/projects/hdall/scripts/remap.pl > current/music/dia/roi_covgs/E_dia.covg &
 cat 2013-05-29-roi-remap/music/dia/roi_covgs/X_dia.covg | perl /mnt/projects/hdall/scripts/remap.pl > current/music/dia/roi_covgs/X_dia.covg &
 cat 2013-05-29-roi-remap/music/dia/roi_covgs/Y_dia.covg | perl /mnt/projects/hdall/scripts/remap.pl > current/music/dia/roi_covgs/Y_dia.covg &

 